#
# This file is part of phpFastCache.
#
# @license MIT License (MIT)
#
# For full copyright and license information, please see the docs/CREDITS.txt file.
#
# @author Khoa Bui (khoaofgod)  <khoaofgod@gmail.com> https://www.phpfastcache.com
# @author Georges.L (Geolim4)  <contact@geolim4.com>
#
os: linux
dist: bionic
language: php
services:
  - memcached
  - redis
  - couchdb
  - riak
  - mongodb

before_script:
  - |
    if [[ $TRAVIS_PHP_VERSION = "hhv"* ]]; then
      cat bin/ci/hhvm_phpfastcache.ini >> /etc/hhvm/php.ini
    else
      pecl channel-update pecl.php.net;
      yes | pecl install -f mongodb-stable;
      yes | pecl install -f memcached;
      yes | pecl install -f apcu-stable || true;
      phpenv config-add bin/ci/php_phpfastcache.ini;
    fi
  - sleep 15
  - mongo pfc_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
    # - php: hhvm
  include:
    - dist: trusty
      php: 7.3
    - dist: trusty
      php: 7.4
  exclude:
    - dist: bionic
      php: 7.3
    - dist: bionic
      php: 7.4
install:
  - ./bin/ci/install_dependencies.sh

script:
  - php -f ./bin/ci/run_tests.php
