#
# This file is part of phpFastCache.
#
# @license MIT License (MIT)
#
# For full copyright and license information, please see the docs/CREDITS.txt file.
#
# @author Khoa Bui (khoaofgod)  <khoaofgod@gmail.com> https://www.phpfastcache.com
# @author Georges.L (Geolim4)  <contact@geolim4.com>
#
os: linux
dist: bionic
language: php
services:
  - memcached
  - redis
  - couchdb
  - mongodb

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
# Memcached is not yet available for PHP8 (hasn't been updated since 2019): https://pecl.php.net/package/memcached
# Memcache however seems to be compatible with PHP 7 and 8: https://pecl.php.net/package/memcache
#
  - |
    echo "\$TRAVIS_PHP_VERSION set to: $TRAVIS_PHP_VERSION";
    pecl channel-update pecl.php.net;
    yes | pecl install -f mongodb-stable;
    yes | pecl install -f apcu-stable || true;
  - |
    if [[ $TRAVIS_PHP_VERSION == "8."* || $TRAVIS_PHP_VERSION == "nightly" ]]; then
        ./bin/ci/scripts/setup_couchbase.sh;
        yes | pecl install -f couchbase-stable;
        yes | pecl install -f memcache;
        phpenv config-add bin/ci/php8_phpfastcache.ini;
    else
        yes | pecl install -f memcached;
        phpenv config-add bin/ci/php7_phpfastcache.ini;
    fi
  - phpenv config-add bin/ci/php_common.ini;
  - phpenv config-rm xdebug.ini
  - ./bin/ci/scripts/setup_mongodb.sh

install:
  - ./bin/ci/scripts/install_dependencies.sh
script:
  - php -f ./bin/ci/run_tests.php
